openapi: 3.1.0
info:
  title: Bootzooka
  version: '1.0'
paths:
  /user/register:
    post:
      tags:
      - user
      operationId: postUserRegister
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
  /user/login:
    post:
      tags:
      - user
      operationId: postUserLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
  /user/logout:
    post:
      tags:
      - user
      operationId: postUserLogout
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Logout_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Logout_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
      security:
      - httpAuth: []
  /user/changepassword:
    post:
      tags:
      - user
      operationId: postUserChangepassword
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePassword_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangePassword_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
      security:
      - httpAuth: []
  /user:
    get:
      tags:
      - user
      operationId: getUser
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUser_OUT'
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
      security:
      - httpAuth: []
    post:
      tags:
      - user
      operationId: postUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUser_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
      security:
      - httpAuth: []
  /passwordreset/reset:
    post:
      tags:
      - passwordreset
      operationId: postPasswordresetReset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordReset_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordReset_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
  /passwordreset/forgot:
    post:
      tags:
      - passwordreset
      operationId: postPasswordresetForgot
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPassword_IN'
        required: true
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForgotPassword_OUT'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
  /admin/version:
    get:
      tags:
      - admin
      operationId: getAdminVersion
      responses:
        '200':
          description: ''
          headers:
            X-Frame-Options:
              required: true
              schema:
                type: string
            Content-Security-Policy:
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version_OUT'
        default:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error_OUT'
components:
  schemas:
    ChangePassword_IN:
      title: ChangePassword_IN
      type: object
      required:
      - currentPassword
      - newPassword
      properties:
        currentPassword:
          type: string
        newPassword:
          type: string
    ChangePassword_OUT:
      title: ChangePassword_OUT
      type: object
      required:
      - apiKey
      properties:
        apiKey:
          type: string
    Error_OUT:
      title: Error_OUT
      type: object
      required:
      - error
      properties:
        error:
          type: string
    ForgotPassword_IN:
      title: ForgotPassword_IN
      type: object
      required:
      - loginOrEmail
      properties:
        loginOrEmail:
          type: string
    ForgotPassword_OUT:
      title: ForgotPassword_OUT
      type: object
    GetUser_OUT:
      title: GetUser_OUT
      type: object
      required:
      - login
      - email
      - createdOn
      properties:
        login:
          type: string
        email:
          type: string
        createdOn:
          type: string
          format: date-time
    Login_IN:
      title: Login_IN
      type: object
      required:
      - loginOrEmail
      - password
      properties:
        loginOrEmail:
          type: string
        password:
          type: string
        apiKeyValidHours:
          type: integer
          format: int32
    Login_OUT:
      title: Login_OUT
      type: object
      required:
      - apiKey
      properties:
        apiKey:
          type: string
    Logout_IN:
      title: Logout_IN
      type: object
      required:
      - apiKey
      properties:
        apiKey:
          type: string
    Logout_OUT:
      title: Logout_OUT
      type: object
    PasswordReset_IN:
      title: PasswordReset_IN
      type: object
      required:
      - code
      - password
      properties:
        code:
          type: string
        password:
          type: string
    PasswordReset_OUT:
      title: PasswordReset_OUT
      type: object
    Register_IN:
      title: Register_IN
      type: object
      required:
      - login
      - email
      - password
      properties:
        login:
          type: string
        email:
          type: string
        password:
          type: string
    Register_OUT:
      title: Register_OUT
      type: object
      required:
      - apiKey
      properties:
        apiKey:
          type: string
    UpdateUser_IN:
      title: UpdateUser_IN
      type: object
      required:
      - login
      - email
      properties:
        login:
          type: string
        email:
          type: string
    UpdateUser_OUT:
      title: UpdateUser_OUT
      type: object
    Version_OUT:
      title: Version_OUT
      type: object
      required:
      - buildSha
      properties:
        buildSha:
          type: string
  securitySchemes:
    httpAuth:
      type: http
      scheme: bearer
