name: Dependabot auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Debug info
        run: |
          echo "PR Actor: ${{ github.actor }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "PR Number: ${{ github.event.pull_request.number }}"

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update PR branch with main
        run: |
          # Update the PR branch to include latest changes from main
          gh pr comment "$PR_URL" --body "🔄 Updating branch with latest changes from main..."

          # This will update the PR branch if it's behind main
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/update-branch"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for all dependency updates
        run: |
          echo "Enabling auto-merge for PR: $PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "Auto-merge enabled successfully"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on PR
        run: |
          gh pr comment "$PR_URL" --body "🤖 Auto-merge enabled. Will merge automatically once all checks pass."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
